# Generated by Django 6.0 on 2026-01-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_name_alter_post_topic_posttestimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posttestimonial',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
